# Generated by Django 4.0.4 on 2022-05-31 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_malhaar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malhaar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 13, 44, 4, 710381, tzinfo=utc)),
        ),
    ]
