# Generated by Django 4.0.4 on 2022-05-31 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_malhaar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malhaar',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 13, 44, 46, 151866, tzinfo=utc)),
        ),
    ]
