# Generated by Django 4.0.4 on 2022-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_user_totalvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malhaar',
            name='volume',
            field=models.FloatField(),
        ),
    ]
