# Generated by Django 4.0.4 on 2022-06-02 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_malhaar_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume', models.FloatField()),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Malhaar',
        ),
    ]
