# Generated by Django 4.0.4 on 2022-06-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_usershower_delete_malhaar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershower',
            old_name='email',
            new_name='user',
        ),
    ]
